require 'pry'
require 'HTTParty'
require 'json'
require 'colorize'

require_relative './cocktails/cli'
require_relative './cocktails/cocktail'
require_relative './cocktails/cocktailAPI'
require_relative './cocktails/category'
require_relative './cocktails/glass'
